### PR TITLE
MEN-4928: improvements to the monitoring UI

### PR DESCRIPTION
**Pull request by tranchitella**
- Improve margins and layout
- Use link instead of button to view logs
- Show the "view logs" link only if there are logs
- Use the right end-point (/alerts/latest)

Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Review by merlin-northern — APPROVED** [review]
I kind of lost track why /alerts was used. I thought it was because it did/suppose to do the proper grouping, but if /latest does the trick, then I am fine with that.

**Comment by tranchitella** [comment]
> I kind of lost track why /alerts was used. I thought it was because it did/suppose to do the proper grouping, but if /latest does the trick, then I am fine with that.

`/alerts` list the records, `/alerts/latest` does the grouping.

**Comment by tranchitella** [comment]
@michaelatmender can you double check it's okay?

**Review by michaelatmender — APPROVED** [review]
This looks good, now I can test it at last!

**Comment by tranchitella** [comment]
@michaelatmender thanks a lot!

**Pull request merged**
