### PR TITLE
improved monitor config absence notification granularity

### PR DESCRIPTION
**Pull request by mzedel**
- this primarily takes existing alerts into account
- unfortunately there is still a chance for the notification to be misleading - especially in case of offline devices

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Review by merlin-northern — APPROVED** [review]
lgtm, I understand that the !isOffline check is on purpose, since we would be unable to show anything.

**Comment by merlin-northern** [comment]
@oleorhagen if you have not started still, this is something we could take into the release and also briefly test.

**Comment by oleorhagen** [comment]
Release is branched out now, so this will have to be cherry-picked if so

**Comment by mzedel** [comment]
that is in already 👌

**Pull request merged**
