### PR TITLE
fixed a problem that could cause a crash of the device lists

### PR DESCRIPTION
**Pull request by mzedel**
this was due to the device inventory being empty and thus a resulting null device in the device list

Changelog: Title
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
Thanks for looking into it. What browser and which browser version did you test this on? the only real change should be the call to `.finally()`, which I fear might be the reason - but group creation shouldn't be different then...

**Comment by michaelatmender** [comment]
> Thanks for looking into it. What browser and which browser version did you test this on? 

Chrome, Version 75.0.3770.100 64 bit. I tested again on master and the issue wasn't there, so it seems to be this PR

**Comment by mzedel** [comment]
that should now be working properly again 😊

**Comment by michaelatmender** [comment]
> that should now be working properly again 😊

Looks good!

**Pull request merged**
