### PR TITLE
MEN-5118 added azure oauth option

### PR DESCRIPTION
**Pull request by mzedel**
Screenshot 2021-10-04 at 11 44 51

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Comment by mzedel** [comment]
Thanks @tranchitella for taking a look! For now I'll leave it unmerged until the backend can be deployed too (I don't want to add another environment flag just for azure)...

**Comment by alfrunes** [comment]
Technically, signup can now be performed by all Microsoft accounts, so maybe s/azure/microsoft/ ? We can ofcourse limit the scope to Azure tenants only, but I see no reason why we should.

**Comment by mzedel** [comment]
Good point @alfrunes - I adjusted the config accordingly 👌

**Comment by tranchitella** [comment]
@mzedel can we merge this PR now that backend support is available?

**Pull request merged**
