### PR TITLE
MEN-4564: update RBAC roles' names to be more descriptive

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Review by kjaskiewiczz — APPROVED** [review]
looks more intuitive

**Review by mzedel — COMMENTED** [review]
while I agree with the _Read Access_ title, I'm torn about the _Release Manager_ as to me this implies UI access, but limited to the releases tab 😕 - whereas I would associate _CI_ with API (release + deployment creation) but not UI access...

**Comment by tranchitella** [comment]
@mzedel isn't it the same with "Deployments Manager"? I tried to make it consistent.

**Review by mzedel — APPROVED** [review]
👍 good point! and I just checked the role config in useradm - my understanding of the role was wrong and _Release Manager_ is indeed very fitting!

**Review by michaelatmender — APPROVED** [review]
This looks clear to me, very good!

**Pull request merged**
