### PR TITLE
fix: fixed an issue that prevented deselecting a release selection during deployment creation

### PR DESCRIPTION
**Pull request by mzedel**
Ticket: None
Changelog: Title

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mzedel could you target 3.5.x? I cant cherry-pick it cleanly.

**Comment by mzedel** [comment]
> @mzedel could you target 3.5.x? I cant cherry-pick it cleanly.

once it's merged to master, but not for this PR

**Comment by merlin-northern** [comment]
> > @mzedel could you target 3.5.x? I cant cherry-pick it cleanly.
> 
> once it's merged to master, but not for this PR

I understand, but if you could create a draft PR so I can easily test with 3.6.0-b12 that would help. sugar pretty plase

**Review by michaelntech — APPROVED** [review]

**Comment by mzedel** [comment]
@mender-test-bot cherry-pick to:
 * 3.6.x

**Pull request merged**
