### PR TITLE
MEN-5104

### PR DESCRIPTION
**Pull request by mzedel**
needs https://github.com/mendersoftware/useradm-enterprise/pull/518 to work...

### CODE REVIEW

**Comment by merlin-northern** [comment]
I gave it a go, says `Password too weak` when I want to create user without password.

**Comment by merlin-northern** [comment]
> I gave it a go, says `Password too weak` when I want to create a user without password. The rest of comments are on slack -- we need to decide how we create the users and how we pass the identity providers and OAuth vs SAML users.

ok I checked a bit and this one sends:

```json
{
  "email": "cooluser@gmail.com",
  "login": "cooluser@gmail.com"
}
```

which currently will not work we expect login to be an object (https://docs.mender.io/api/#management-api-user-administration-and-authentication-schemas-usernew). I will follow-up with the team today on how we want to create the users from the UI point of view.

**Comment by merlin-northern** [comment]
cutting the long story short: please send just emails:

```
{
  "email": "msmith@samltest.id"
}
```

**Review by tranchitella — APPROVED** [review]

**Review by merlin-northern — COMMENTED** [review]
I tested it with useradm-enterprise latest changes, but it still shows "Password too weak", let's you create the user without password, but the error is visible right before the dialog disappears, perhaps around here: https://github.com/mendersoftware/gui/blob/master/src/js/components/common/forms/form.js#L104 we could not show the too_weak error if password is empty?

**Comment by mzedel** [comment]
@merlin-northern should now be fixed! I'll bring it to staging so we can give it a go 😃

**Comment by merlin-northern** [comment]
> @merlin-northern should now be fixed! I'll bring it to staging so we can give it a go 😃

yes it is lovely now!

**Pull request merged**
