### PR TITLE
long device inventory texts are no longer cut off + visible on hover

### PR DESCRIPTION
**Pull request by mzedel**
Changelog: Title
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by michaelatmender** [comment]
@mzedel, I had already created a task for this before I realised you were working on it already: https://tracker.mender.io/browse/MEN-2415
I think it would be improved a little with allowing to click to expand/hide as described in the ticket, do you think it could be adjusted easily?

**Comment by mzedel** [comment]
yep, I'll change that - the expand/ hide click would definitely be better and should not take long to adjust

**Comment by michaelatmender** [comment]
Testing locally, I can't see the' behaviour proposed the ticket. It shows the full value all the time, and there is no "show more" or "show less" link.

**Comment by mzedel** [comment]
Now I added the "show less" and "show more" links and they are only visible if it would not be possible to show the whole text in one line. However, this depends on the window size at the time of mounting the component. So if you expand the attribute list and change the window size, the link will not be directly visible only once you close & re-expand the list. If the window size remains unchanged everything should work as expected.
For values that span multiple lines, we would need a fixed number of lines to force a cutoff, detect the cutoff and make it expandable. I think it might be valuable to show the full value if it is not cutoff and only provide the expansion as a workaround for the cutoff case. What do you think @michaelatmender ?

**Comment by michaelatmender** [comment]
Previously it showed 2 lines and ellipsis "..." if the value was too long even for 2 lines. I think we keep that the same but add the "show more" link after the ellipsis. I still have problems with this PR, will describe in the ticket.

**Pull request merged**
