### PR TITLE
We introduced "retry" as a concept after this label, which was a

### PR DESCRIPTION
**Pull request by estenberg**
short-term solution. Recreate deployment should better explain
what it does vs. today's per-device automatic retry.

### CODE REVIEW

**Comment by estenberg** [comment]
Screenshot from 2021-01-14 09-57-49

**Comment by estenberg** [comment]
Hopefully simple change to reword "Retry deployment" in this screen to "Recreate deployment".

It did not seem to be mentioned anywhere else nor have any dependencies, so hoping this is as simple as it looks. :)

**Comment by mzedel** [comment]
Ah right, that should clear up some of the confusion around the retries 👍
Unfortunately the license page in the docs site is currently having problems (fix is in https://github.com/mendersoftware/mender-docs/pull/1286), due to the link checking in the UI, the pipeline will likely only be able to succeed tomorrow morning (I think).

One tiny thing though: the `Changelog` tag is missing in your commit, I'll happily add it if you haven't done so before the docs issue is fixed...

**Comment by estenberg** [comment]
Great, thank you @mzedel !
I have fixed the changelog, it is too long between I commit these days so I forgot :)

**Review by mzedel — APPROVED** [review]

**Pull request merged**
