### PR TITLE
moved e2e tests from integration repo to gui

### PR DESCRIPTION
**Pull request by mzedel**
this is to allow aligning ui checks with gui content/ layout changes
adjust ci script accordingly

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
This is mainly to prevent issues like the failure in https://github.com/mendersoftware/gui/pull/610 in the future and while the integration repo does not yet call the tests in a different pipeline, the test definitions living in this repo seems to be better suited IMHO.

**Comment by lluiscampos** [comment]
> This is mainly to prevent issues like the failure in #610 in the future and while the integration repo does not yet call the tests in a different pipeline, the test definitions living in this repo seems to be better suited IMHO.

I agree with this. From my point of view, conceptually these are "acceptance" tests and they should live in this repo.

**Comment by mzedel** [comment]
The `WARNING: tests/e2e_tests/cypress/screenshots: no matching files` should only have matching files if there was an error during testing (otherwise there should not be screenshots). Do you know how to set this conditionally?

And yes, I'll remove them from the integration repo once this is merged and cherry picked to the 2.2.x branch. Thanks for the heads up!

**Comment by lluiscampos** [comment]
> The `WARNING: tests/e2e_tests/cypress/screenshots: no matching files` should only have matching files if there was an error during testing (otherwise there should not be screenshots). 

Thanks for clarifying.

> Do you know how to set this conditionally?

I don't think it is possible.

**Pull request merged**
