### PR TITLE
print request ID to snackbar when a request fails

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@michaelatmender this isn't 100% done, but needs to be carefully reviewed

**Comment by michaelatmender** [comment]
The first login error snackbar isn't showing using this PR (for example if user doesn't exist)

**Comment by GregorioDiStefano** [comment]
Updated

**Comment by GregorioDiStefano** [comment]
@michaelatmender i think this is ready to merge, I fixed the issues you found and tested it more.

**Pull request merged**
