### PR TITLE
MEN-3857: improve the create new group modal

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Review by michaelatmender — CHANGES_REQUESTED** [review]
I commented on MEN-3857: I think this approach re-introduces some UX issues that caused the change initially. See the ticket for my suggestion!

**Comment by tranchitella** [comment]
@mzedel @michaelatmender I reworked the PR to follow the comments and mockup in the ticket.

**Comment by michaelatmender** [comment]
Great, thanks! Just one nitpick left from me - when typing a new group name that also matches the start of an existing group, the 'create "x" group' option doesn't show (see https://tinyurl.com/y5pgxzgw for an example). It's maybe not likely to happen often, but it would be good to display the option consistently if possible.

**Comment by tranchitella** [comment]
> Great, thanks! Just one nitpick left from me - when typing a new group name that also matches the start of an existing group, the 'create "x" group' option doesn't show (see https://tinyurl.com/y5pgxzgw for an example). It's maybe not likely to happen often, but it would be good to display the option consistently if possible.

Updated!

**Review by michaelatmender — APPROVED** [review]

**Pull request merged**
