### PR TITLE
MEN-6487 - fix: added more granular check for device troubleshooting feature

### PR DESCRIPTION
**Pull request by mzedel**
Ticket: MEN-6487
Changelog: Title

### CODE REVIEW

**Review by michaelatmender — CHANGES_REQUESTED** [review]
Testing this, and I still see the File Transfer UI even as a user with no troubleshooting/connect permissions

**Comment by michaelatmender** [comment]
> > Testing this, and I still see the File Transfer UI even as a user with no troubleshooting/connect permissions
> 
> yes, since read access to devices should still allow you to download files from a device...

Got it! That makes sense. Perhaps we shouldn't show the 'upload' tab in this case? That can be a separate ticket though

**Comment by mzedel** [comment]
Thanks for the review @michaelatmender - I adjusted the dialog to take this into account 👌

**Comment by michaelatmender** [comment]
> Thanks for the review @michaelatmender - I adjusted the dialog to take this into account 👌
Almost there! It still loads the file upload view by default for Read-only users: 
image

Otherwise, all good

**Review by michaelatmender — APPROVED** [review]

**Pull request merged**
