### PR TITLE
 ME-26 - fix stale toggling calls

### PR DESCRIPTION
**Pull request by mzedel**
this mostly just moves state toggling calls to the updater function syntax, reusing a [shared toggle function](https://github.com/mendersoftware/gui/pull/3220/files#diff-78de060e341c3e5d69057a823256ad1d39b665f91a295c60e9528a45757413f5R258), in areas where the value to be toggled was used in another call, both were wrapped in a `useCallback` hook to ensure the values are updated...

### CODE REVIEW

**Comment by estape11** [comment]
Hey @mzedel 😊, I am curious about the status of this PR, is still in WIP?

**Comment by mzedel** [comment]
@estape11 yes, unfortunately I haven't gotten to work on this in the meantime, as soon as I work on this there will be updates to this PR

**Comment by estape11** [comment]
> @estape11 yes, unfortunately I haven't gotten to work on this in the meantime, as soon as I work on this there will be updates to this PR

I understand, thank you for the update Manuel 😊

**Review by tranchitella — APPROVED** [review]
Looks good and runs fine; however, one request if it is possible: sorting the imports in a different commit could have speeded up the review process quite a bit.

**Pull request merged**
