### PR TITLE
MEN-4364: fix page number quick on rowsPerPage change

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mzedel ping (we need this in the release)

**Comment by mzedel** [comment]
unfortunately that breaks the page counting as the page will be 0 if the component stays mounted but the page number changes... I'll have the fix ready soon...

**Comment by tranchitella** [comment]
@mzedel oh, right... sorry.

**Comment by tranchitella** [comment]
Superseded by https://github.com/mendersoftware/gui/pull/1236

**Pull request closed without merging**
