### PR TITLE
MEN-3600: Fix incorrect installation instructions for Enterprise demo.

### PR DESCRIPTION
**Pull request by kacf**
The demo for Enterprise is not officially supported, but we use it for
internal testing, therefore this is important.

Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
This generates the following instructions. For Open Source:

```bash
sudo bash -c 'wget https://d1b0l86ne08fsf.cloudfront.net/2.3.0b1-build2/dist-packages/debian/armhf/mender-client_2.3.0b1-build2-1_armhf.deb && \
DEBIAN_FRONTEND=noninteractive dpkg -i --force-confdef --force-confold mender-client_2.3.0b1-build2-1_armhf.deb && \
DEVICE_TYPE="raspberrypi3" && \
mender setup \
  --device-type $DEVICE_TYPE \
  --quiet --demo --server-ip 192.168.1.20 && \
systemctl restart mender-client'
```

For Enterprise:
```bash
sudo bash -c 'wget https://d1b0l86ne08fsf.cloudfront.net/2.3.0b1-build2/dist-packages/debian/armhf/mender-client_2.3.0b1-build2-1_armhf.deb && \
DEBIAN_FRONTEND=noninteractive dpkg -i --force-confdef --force-confold mender-client_2.3.0b1-build2-1_armhf.deb && \
DEVICE_TYPE="raspberrypi3" && \
TENANT_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW5kZXIudGVuYW50IjoiNWVjZjg1N2YxNjJhZGI0NWNjOWFhZDU1IiwiaXNzIjoiTWVuZGVyIiwic3ViIjoiNWVjZjg1N2YxNjJhZGI0NWNjOWFhZDU1In0.tZV-GMzUKaDs32DtCUFoDAEj-XUe_AuAUZO5VZX_qhoaxzZvsKKlGv5GYQo3pXOocsgwWI2XoLuCd-TsNenNpExG1aWFmMfPB6HSb6VLNiZGKda6DykrgJ2c8Ibq3H5U4REebWXOg71isMcYpwoa0-s_rk_IXvRtucNKWqIwa_PjZA-PJi0Xvd6PKZWk1DoifP4fXArTjwQsOyIcPoymvZico006QU0GhejhUSW2C5uHlmoCI7yC3SGWGY6kiC5rKOl9S9A75dp91q7E7eqMIihi_iIcLVrf-7gwbdhGkKlM1DXMYjWX-WFlpXCIucN--qftAUFOWeUxmR-Pd43KYFdYcl2lMwVkqM7g3_ZoUg_nTF-Jsf7BlOme_d62qOizkXJV0Abf913mHhsKhxL3aToIBwKJ3O_qegpqPZ8Jz10yGdHF675m2O4eNyQQiNlbWdERvFAhEgZfoam3juRxdxso8MhkBJlP_Ju_ilu08Aw4e-faEi6WGIPbKFWO37xv" && \
mender setup \
  --device-type $DEVICE_TYPE \
  --quiet --demo   --server-ip 192.168.1.20 \
  --tenant-token $TENANT_TOKEN && \
systemctl restart mender-client'
```

For Hosted:
```bash
sudo bash -c 'wget https://d1b0l86ne08fsf.cloudfront.net/2.3.0b1-build2/dist-packages/debian/armhf/mender-client_2.3.0b1-build2-1_armhf.deb && \
DEBIAN_FRONTEND=noninteractive dpkg -i --force-confdef --force-confold mender-client_2.3.0b1-build2-1_armhf.deb && \
DEVICE_TYPE="raspberrypi3" && \
TENANT_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW5kZXIudGVuYW50IjoiNWVjZjgzYWU4MWFkN2RjMWFhM2JkMjM1IiwiaXNzIjoiTWVuZGVyIiwic3ViIjoiNWVjZjgzYWU4MWFkN2RjMWFhM2JkMjM1In0.Rx4L8RgjbPSMWV8d2wvHgXZJgv-IRnbJmaOnT1Pp7adqDZ8kpACc4eYAqjjYe4ltWPJvAqcBrW9ZGmGvVnWEk2eIWcOfIOdrw61p06u5Xt5Fdywk13viLDSbRC1E7mz2OMJNMUDm0mXOcT-YVSapngPHYnHaHblI6N-lZXs-E3WKu0ThadUvgrjrSzIo155Qbaev5sBHyLJVpsFLRfHmd48Y671_HQ9xfI_eDxLhy3VEYFRWHa5I78hl5VWmg-eTzybGy98-ExoAV-GWQbF20qPxvWKIiYf-P7TI-ZNa20h0TbPnjfUJHiQjP8peLvDsjcWnTlo9h63OFA3rrtmCDVOOeI5RSTcT9Ew3W5P_TtzNwiXIplErwC6pKz9dqLRqgJ_RWVxUYQHMDXYygmLe0-b-bwENS68YfZwYZ8Q3egK854h0D8XAXXrGSyWeSiB3H1ImIZYHsKfGVTcHjv92M5XzTd5xc92ESIK9t3YCrXB_OVbISaizR1b8nmOj2ZP3" && \
mender setup \
  --device-type $DEVICE_TYPE \
  --quiet --hosted-mender \
  --tenant-token $TENANT_TOKEN \
  --retry-poll 30 \
  --update-poll 5 \
  --inventory-poll 5 && \
systemctl restart mender-client'
```

Open Source and Enterprise were verified working. I have not tested Hosted, but I believe the command line ends up the same as before.

**Comment by kacf** [comment]
Hold on, I will change it a little bit to line up better, to share the settings for demo setups, and to match the test expectations.

**Comment by kacf** [comment]
Updated! Open Source and Enterprise were verified again, and Hosted Mender looks like this:
```bash
sudo bash -c 'wget https://d1b0l86ne08fsf.cloudfront.net/2.3.0b1-build2/dist-packages/debian/armhf/mender-client_2.3.0b1-build2-1_armhf.deb && \
DEBIAN_FRONTEND=noninteractive dpkg -i --force-confdef --force-confold mender-client_2.3.0b1-build2-1_armhf.deb && \
DEVICE_TYPE="raspberrypi3" && \
TENANT_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW5kZXIudGVuYW50IjoiNWVjZjkxOWM2YmIzYzJhODAyYmU2YjAyIiwiaXNzIjoiTWVuZGVyIiwic3ViIjoiNWVjZjkxOWM2YmIzYzJhODAyYmU2YjAyIn0.gfOpDzJdwRoJIVYPazBUAueW5fAv5S81LEgK54IxbepJtK1du7lvCkCrjiuVQvPCMMCbAtwnQyEUuqRecHezc-ih3UnLTSzlMspWRJiT3JMeqWERIoKDiN2l-X5QyqCS8FT-J0ooYtNde-CrgxtzDbzVvQ_ZqYLXGXRNSVCx2xQUL5fEDdSJsL07cS0Fk2Eu6mARlMOmruZ1cvfOjaGBQT3W4ZYiO2uZQrPYDFScq8eELGPhiqVjBjIaHrBHpawFb5Q6Gt46NAceopXblV4EH5Fy1Kbftwszuwzm8g48WiyA05sV7XexqyAfKxC9PBJnE5apXOm2SJaXjRphqZDr2vh0BaGS7VPjlOItJGsa_AgfjZVz2SsFZnBmEM1vx2gI5PVZAvKnCu32iskAQEtmuE0stIcJh5fvmF6ghoE4aKUSWQ__qGItjD2QwA3JoDCaoDrQ4LNN-G7gf4nnHrsc72TgH8aguAYKgucxvAa2YC9uYF7spdAdAvhLmddB6zJh" && \
mender setup \
  --device-type $DEVICE_TYPE \
  --quiet --hosted-mender \
  --tenant-token $TENANT_TOKEN \
  --retry-poll 30 \
  --update-poll 5 \
  --inventory-poll 5 && \
systemctl restart mender-client'
```

**Comment by kacf** [comment]
> I can verify that the new instructions works for hosted mender as well.

Great, thanks, the new instructions are identical, so then we are good!

**Comment by kacf** [comment]
@mzedel: Is the failure relevant? It's talking about password changes...

**Comment by mzedel** [comment]
@kacf that happens sometimes if the build slave in use is under heavy load, which may cause requests to fail and subsequently the tests... #694 will address this (so that we can use the gitlab runners for this stage as well), but needs some additional work...

**Comment by kacf** [comment]
Alright, thanks!

**Pull request merged**
