### PR TITLE
MEN-6551 - fix: fixed an issue that prevented re-opening the search result for an unchanged search term

### PR DESCRIPTION
**Pull request by mzedel**
- also made search require 2 letters to start, since the search backend doesn't work reliably with a single letter

Ticket: MEN-6551
Changelog: Title

### CODE REVIEW

**Review by lluiscampos — COMMENTED** [review]
It might be something off with the setup, but it doesn't seem to work as expected on my demo setup. I have two devices and the search for a unique Device ID returns the two devices (I suspect that it returns _all_ the devices)

image

**Review by lluiscampos — CHANGES_REQUESTED** [review]
It might be something off with the setup, but it doesn't seem to work as expected on my demo setup. I have two devices and the search for a unique Device ID returns the two devices (I suspect that it returns _all_ the devices)

image

**Comment by lluiscampos** [comment]
@mzedel You are totally right - the backend returns all the devices

image
image

**Review by lluiscampos — APPROVED** [review]

**Comment by mzedel** [comment]
@aleksandrychev this like too

**Pull request merged**
