### PR TITLE
MEN-3917 - deployment size

### PR DESCRIPTION
**Pull request by mzedel**
FYI @kjaskiewiczz

### CODE REVIEW

**Comment by tranchitella** [comment]
This is misbehaving, look at the progress bars:

image

**Comment by mzedel** [comment]
Thanks for taking a look @tranchitella! These issues should now be fixed 👌

**Comment by tranchitella** [comment]
@mzedel I must be doing something wrong because I still don't get the sizes in the UI, and the progress bars are misaligned:

image

Am I running the right PR?

**Review by tranchitella — APPROVED** [review]
I love you, man.

**Pull request merged**
