### PR TITLE
fix: fix filterable attributes bar behavior when count is bigger than limit

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
Ticket: [MEN-6212](https://tracker.mender.io/browse/MEN-6212)

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
not sure that's the right solution, but at least it's very cheap

**Review by mzedel — APPROVED** [review]
As a preventive measure this might be ok, but it masks a broken backend and should be fixed there.

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
> As a preventive measure this might be ok, but it masks a broken backend and should be fixed there.

@mzedel and @kjaskiewiczz, here is the fix in the backend which prevents to return more attributes than the limit:
https://github.com/mendersoftware/reporting/pull/91

**Review by tranchitella — CHANGES_REQUESTED** [review]
Let's drop this one and fix it in the backend.

**Pull request closed without merging**
