### PR TITLE
Fix broken URL at end of onboarding to system updates.

### PR DESCRIPTION
**Pull request by estenberg**
NOTE: This will not work for Hosted Mender, so should probably
change it (but at least it is not broken with this change).

Changelog: None

Signed-off-by: Eystein Måløy Stenberg <eystein.maloy.stenberg@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
this now depends on https://github.com/estenberg/gui/pull/1 to get merged, then this should get green tests & get merged right away

**Comment by estenberg** [comment]
Thanks @mzedel 
I merged your PR, can you please merge this one if ok now?

**Comment by estenberg** [comment]
Also feel free to pick this change and close this PR if it's easier :)
I honestly don't quite understand all the merges & dependencies required here.

**Comment by mzedel** [comment]
closing in favour of #582

**Pull request closed without merging**
