### PR TITLE
ci: made disclaimer reuse existing image layers.

### PR DESCRIPTION
**Pull request by mzedel**
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
needs https://github.com/mendersoftware/mendertesting/pull/207

**Comment by mzedel** [comment]
@mender-test-bot start pipeline just to check the buildkit effects please!

**Comment by mzedel** [comment]
@tranchitella just to clarify the motivation for this: the disclaimer build is quite a time sink in the staging pipeline when you're eager to test a change 😅 - with this in, the job is a lot quicker...

**Review by tranchitella — APPROVED** [review]
Makes sense.

**Pull request merged**
