### PR TITLE
MEN-6034 - tabbed device details

### PR DESCRIPTION
**Pull request by mzedel**

### CODE REVIEW

**Comment by tranchitella** [comment]
@mzedel there is a strange label "Device actions" here:
image

Why?

**Comment by tranchitella** [comment]
Below Monitoring and Troubleshooting's title there is a paragraph starting with the info icon.
These paragraphs are not aligned with each other, and when moving between the tabs you can detect it.
I know, this is a tiny issue, but still...

**Comment by mzedel** [comment]
Thanks a lot for checking so quick @tranchitella! I'll adjust the alignment issue right away, but:

> @mzedel there is a strange label "Device actions" 

that should be the title of the floating action button... that _should_ be on top of the slide out, right next to the label 🧐

**Comment by tranchitella** [comment]
@mzedel alignments are good, but I don't see how this label should be positioned on top of the floating menu.

image

and...

image

**Comment by mzedel** [comment]
@tranchitella the screenshot pointed me in the right direction... Chrome 108 seems to render this differently - I had 107 and it looked as intended, with 108 there seems to be something changed... I'm looking into it!

**Comment by mzedel** [comment]
@tranchitella now it should work 🤞

**Review by tranchitella — APPROVED** [review]
Confirmed, it works fine... and the tabs are lovely.
EDIT: I retested after the force-push, but couldn't spot any difference...

**Pull request merged**
